### ISSUE TITLE
Text doesn't render properly on the home page

### ISSUE THREAD

**Issue by Infinitay** [happyendermangit/discarchives#2]
![image](https://github.com/happyendermangit/discarchives/assets/6964154/aad17a55-5d66-464c-bfd7-dfcd86302fa8)

I can only see the text in the Navigation menu if I over over the buttons and I can only see the text on the page if I select it/all the text.

**Comment by wavedevgit** [comment]
I forgot to make the default theme dark

**Comment by wavedevgit** [comment]
thanks for opening the issue!

**Comment by wavedevgit** [comment]
Fixed on [#e662550fc1c552ec4dc4e3b57b98ee6e76d4490e](https://github.com/happyendermangit/discarchives/commit/e662550fc1c552ec4dc4e3b57b98ee6e76d4490e)
